## pandas

#### pandas is a library which is used for data analysis. It can perform many functions like sorting, filtering and it is used to clean messy data efficiently.

#### pandas can be used by importing the pandas library. A common alias used for pandas is pd. Similar to np for numpy.

In [2]:
import pandas as pd

## Series, DataFrame
#### Both are the common and most important Data Structures in pandas.
#### Series(data, index=[<Row_Labels>])
#### DataFrame({col1: Values, Col2: Values, ...})

#### Series is a 1D labeled array, so it can store 1 column of data.
#### DataFrame is a 2D labeled array, so it can store in rows and columns format.

#### Example use case for AI:
#### Series can be used as a target column

In [1]:
import pandas as pd

y = pd.Series([10000000, 20000000, 15000000, 85000000])
y

0    10000000
1    20000000
2    15000000
3    85000000
dtype: int64

#### y can be a target variable which can store the prices of a house for house prediction task.

#### Similarly, DataFrame() is used to store a set of features. For example:

In [2]:
import pandas as pd

X = pd.DataFrame({
    "sqft": [1400, 2400, 2200, 1200],
    "bedroom": [2, 3, 3, 2],
    "bathroom": [1, 2, 2, 1]
})

X

   sqft  bedroom  bathroom
0  1400        2         1
1  2400        3         2
2  2200        3         2
3  1200        2         1

## ii) pd.read_csv() and pd.read_excel()
#### pd.read_csv() is used to read a comma seperated value file and load it into a DataFrame for easier data processing.
#### Example, in the datasets/house_details.csv, the same data which is used in the DataFrame() code snippet is used. 
#### Almost all the time, the DataFrame is loaded from an external source like a csv file.

In [7]:
import pandas as pd

df = pd.read_csv("datasets/house_details.csv")
df

   sqft  bedroom  bathroom
0  1400        2         1
1  2200        3         2
2  2400        3         2
3  1200        2         1

#### df is another common accronym used for 'DataFrame'

## iii) head(), tail()
#### head(n) will display the first n records (or rows) of the DataFrame. Default value of n is 5.
#### tail(n) will display the last n records (or rows) of the DataFrame. Default value of n is 5.
#### Both of these are useful if we want to know how the data is stored and what the features are.

In [8]:
import pandas as pd
import numpy as np


arr = np.arange(1, 101, 1)
df = pd.Series(arr)

print("Using head():")
print(df.head())
print()
print("Using tail():")
print(df.tail())

Using head():
0    1
1    2
2    3
3    4
4    5
dtype: int32

Using tail():
95     96
96     97
97     98
98     99
99    100
dtype: int32

## iv) describe(), info()
#### describe() gives the important statistics data. It gives the following:
#### a) count - number of records in the dataframe
#### b) mean - mean of the column (if it is numerical)
#### c) std - standard deviation of the column
#### d) min, max - minimum and maximum value in the column
#### e) 25%, 50%, 75% - the 25th, 50th, 75th percentile of the column

#### info() gives the description of the dataframe including the column name, datatype, number of indexes (rows)

In [15]:
import pandas as pd
import numpy as np


arr = np.arange(1, 101, 1)
df = pd.Series(arr)

print(df.describe())
print()
print("Using info():")
print(df.info())

count    100.000000
mean      50.500000
std       29.011492
min        1.000000
25%       25.750000
50%       50.500000
75%       75.250000
max      100.000000
dtype: float64

Using info():
<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: None
Non-Null Count  Dtype
--------------  -----
100 non-null    int32
dtypes: int32(1)
memory usage: 528.0 bytes
None